<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="HP" name="Testcases.Amazontestcase" tests="5" failures="0" timestamp="27 Jul 2020 07:36:36 GMT" time="1.941" errors="1">
  <testcase name="URLLaunch" time="1.941" classname="Testcases.Amazontestcase">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: URLLaunch([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) https://amazon.in,(java.lang.String) vignesh186v@gmail.com,(java.lang.String) Pass@12345]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: URLLaunch([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) https://amazon.in,(java.lang.String) vignesh186v@gmail.com,(java.lang.String) Pass@12345]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:983)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- URLLaunch -->
  <testcase name="verifytitle" classname="Testcases.Amazontestcase">
    <skipped/>
  </testcase> <!-- verifytitle -->
  <testcase name="Applogout" classname="Testcases.Amazontestcase">
    <skipped/>
  </testcase> <!-- Applogout -->
  <testcase name="Applogin" classname="Testcases.Amazontestcase">
    <skipped/>
  </testcase> <!-- Applogin -->
  <testcase name="Prodprice" classname="Testcases.Amazontestcase">
    <skipped/>
  </testcase> <!-- Prodprice -->
</testsuite> <!-- Testcases.Amazontestcase -->
